language: node_js
node_js:
- '0.12'
sudo: false
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: heroku
  api_key:
    secure: Va5HzKgJMCBTanO0G+OTh5RIlxRqlZ4foVmrwvFrxurPbT6dmGDcwslGa4BG3oGQrqZXhIqwgYK6JLgF0YKRfy2BxewRFsGMX5ux1I4aKx+LKvRlb1QUpfjJT6hwCKPFIBUMr6xd9q/ZYsHvaJtnCccN7gjoc6b8h8PSx89djlffQDfphhrD9TUUIqkJlYrBXsRMMdWd692Pn0Uct4Q0uIxWtFGq9PRFdOmmt4PxBdObUwzAFX6bAJEXE4k5I+5kRs4B58ev5zOhvNB8UANJ2/jBqhJPxwwcbAtx4Kl1KS3+TYzhEF3NQCCWlwsd6c4IF6R/nvCCBuR0KEE2sCmsEqJwTc+QPd1ZjAnhj2QoLpCqzT5bu0P4Quy7uDncKfpWTySridQiYN1vMxZkSQAPc5Awm3NJJ59gXfNysqWFwq6l+a9NPEK2JnY6eIBUoWlqatnumkdZjtfw1weuhKPZXqhEIzwhM62IQM2JxuCTVrD4LANnU9xInO+XXdiMbX7SqM703dxxLS20JqYAwWE/vssETtIlbZPssrBUpKCiejFRdxYeHkDMKcgobHIq4LYrKtU9A7ua3C5ztC2Lk3MjiPpWlHsZg3k0xV+SmeOTyP1E9u2Bk5o4MRLs9ZHoXniCikuDuqxnz3RAA40WUAxZgXylanLE5p/aFOS03FuCfmM=
  app: stormy-castle-6464
  on:
    repo: samlawrencejones/jhipster
